### ISSUE TITLE
[Bug] - No upper limit on page number

### ISSUE THREAD

**Issue by Luke9389** [TellemBigAlsentya/local-storage-favorites#5]
Currently, there is a guard clause preventing the user from decrementing the page number lower than `1`.

https://github.com/TellemBigAlsentya/local-storage-favorites/blob/8d48115ede34b93bb94d3e0d2838186582c078a2/app.js#L35

Could we introduce a similar guard clause to prevent the user from incrementing the page number too high? 

🤔 **Note:** In the event of a new season of Rick & Morty, there may be more characters introduced to the API. We should attempt a solution that will be "future proof". In other words, we should not have to edit our front end every time the API content changes.

**Comment by alexhoffman-dev** [comment]
In thinking about your note, I'd like to implement an algorithm where the guard clauses for the page buttons disable them from being clicked altogether. Currently, our guard clause sets currentPage to 1 and subsequently makes a new network request/fires getData() despite us already having access to and showing said data. 

I'd like to suggest employing a helper function to create a guard clause using the next and previous page data from each API response via parsedResponse.info. The API gives us a next and previous page value in the event that we are incrementing our fetch via the prev/next page buttons in our app. This helper function acts as a switchboard for implementing changes to the relevant DOM elements; ie. if the returned object for parsedResponse.info has no next-page key, the next page button is greyed out and does not call the page() function. 

Since the API response already formats this data for us, using said helper function will also help guard against a related BUG in our app, which is that the user is able to call the page() function after using the search functionality. I'm of the opinion that if a user is searching for characters, they won't need the next/prev page buttons since all of the relevant character card data is returned via that specific API fetch. 

I'd like to suggest the following workflow: 
- [ ] - create a helper function using parsedResponse.info as a parameter
- [ ] - check the truthiness of that object and nested key-value pairs --> change UI accordingly

**Comment by Luke9389** [comment]
This sounds great. 👍

On which line do you envision calling that helper function?

**Comment by alexhoffman-dev** [comment]
I think that line 32.5 is where we want that helper function. Looking at this again, I think that including an early return on line 34.5 will also work to prevent unnecessary network requests as a quick fix. 

That said, employing a helper function that checks the truthiness of a next/previous page key value, will also help eliminate any bugs at the high end of our paginated API fetch. In the case that the Rick and Morty API adds more characters, this fix should also be future proof.

**Comment by Luke9389** [comment]
I think calling a helper in the `page` function would totally work. There is one hiccup though. `page` is called **after** someone clicks one of the buttons (`Next Page` & `Previous Page`). It might be even better to disable those buttons entirely. For example, we could have the helper function check the `parsedResponse.info` in the `showData` method (somewhere around line 104.5) and then disable any applicable buttons.

The current process is:
1. Get data
2. Show data (i.e. update the grid)

The new process would be:
1. Get data
2. Show data -> update the grid AND the prev & next buttons

**Comment by Luke9389** [comment]
LMK if I should elaborate more on where and how to do that. 
If it sounds like something you can run with, feel free to start a branch and make a PR (happy to help w/ that part too).

**Comment by alexhoffman-dev** [comment]
> The current process is:
> 
> 1. Get data
> 2. Show data (i.e. update the grid)
> 
> The new process would be:
> 
> 1. Get data
> 2. Show data -> update the grid AND the prev & next buttons

I totally agree with this new process for updating the UI. That said, it strikes me that the guard clause for preventing users from making extraneous network requests at the upper/lower limits of the paginated data from the API and disabling applicable buttons, could be separate functionality. I've built the following helper function for line 33.5 which I think is a better guard clause for our `page` function. 

`function paginationCheck(pageButton) {  
    if(pageButton === 'next-page' && currentPageData.next) {
        return true; 
    } else if(pageButton === 'previous-page' && currentPageData.previous) {
        return true;
    } else {return false;}
}`

**Comment by alexhoffman-dev** [comment]
haha looks like I need to learn how to drop formatted code into my GitHub comments -- I'd also totally take you up on the offer to help me make a branch and PR for this work I'm doing right now so I can share more easily :)

**Comment by Luke9389** [comment]
Ok awesome! Lets do this discussion on the PR. 

To drop formatted code you can wrap it with triple back ticks ```

You can also color code it based on the language with ``` js (sql and many others work as well)

You can also use the menu on any comment to edit it and see how ppl are using syntax (even other ppls' comments). Try it with this one!

Examples:

```js
    function example() {
        console.log('yoyoyoy');
    }
```

```sql
SELECT * FROM accounts WHERE accountID = '3';
```
